#
# Copyright Soramitsu Co., 2021-2023
# Copyright Quadrivium Co., 2023
# All Rights Reserved
# SPDX-License-Identifier: Apache-2.0
#

name: Clang Tidy

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
      name: checkout
      with:
        submodules: true
        clean: true
        fetch-depth: 1
    - name: install
      run: |
        set -e
        sudo apt-get update || true
        sudo apt-get install -y ninja-build gcovr gcc-13 g++-13 clang-15 clang++-15 llvm-15

        sudo update-alternatives --install /usr/bin/python       python       /usr/bin/python3               90
        sudo update-alternatives --install /usr/bin/clang-tidy   clang-tidy   /usr/bin/clang-tidy-15         999 
        sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-15       999 
        sudo update-alternatives --install /usr/bin/clang        clang        /usr/lib/llvm-15/bin/clang-15  999
        sudo update-alternatives --install /usr/bin/clang++      clang++      /usr/bin/clang++-15            999
        sudo update-alternatives --install /usr/bin/gcc          gcc          /usr/bin/gcc-13                90
        sudo update-alternatives --install /usr/bin/g++          g++          /usr/bin/g++-13                90
        sudo update-alternatives --install /usr/bin/gcov         gcov         /usr/bin/gcov-13               90

        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install scikit-build
        sudo python3 -m pip install cmake==3.25 requests gitpython gcovr pyyaml
    - name: run checks
      run: |
        #!/bin/bash
        LLVM_DIR=/usr/lib/llvm-??
        VER_COUNT=$(ls -d -1 ${LLVM_DIR} | wc -l)
        test ${VER_COUNT} -eq 0 && echo "no llvm version detected" && exit 1
        export LLVM_ROOT=$(ls -r -d -1 ${LLVM_DIR} | head -1)
        export PATH=${LLVM_ROOT}/bin:${LLVM_ROOT}/share/clang:${PATH}
        cmake . -Bbuild
        .github/aux/clang-tidy.sh build
